const theme = {
  config: {
    useColorSchemeMediaQuery: 'system' as const,
  },
  fonts: {
    body: 'Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    heading: '"Avenir Next", sans-serif',
    monospace: 'Menlo, monospace',
  },
  colors: {
    'header-bg': '#3182ce',
    'input-bg': '#2b6cb0',
    'input-color': '#63b3ed',
    blue: '#3182ce',
    text: '#fff',
    background: '#000',
    primary: '#33e',
    highlight: '#0c1a1f',
    muted: '#191919',
    overlay: 'rgba(0, 0, 0, 0.7)',
    'background-primary': '#1A202C',
    'background-secondary': '#171923',
    'interactive-accent': '#4299e1',
    'interactive-accentHover': '#63b3ed',
    'background-hover': '#1A202C',
    'text-primary': '#fff',
    'text-heading': '#f8f9fd',
    'text-danger': '#FC8181',
    'text-muted': '#CBD5E0',
    'background-modifier-border': '#2D3748',
    'sidebar-text': '#CBD5E0',
    'border-color': 'rgba(255, 255, 255, 0.16)',
    modes: {
      dark: {
        blue: '#3182ce',
        text: '#fff',
        background: '#000',
        primary: '#33e',
        highlight: '#0c1a1f',
        muted: '#191919',
        overlay: 'rgba(0, 0, 0, 0.7)',
        'background-primary': '#1A202C',
        'background-secondary': '#171923',
        'interactive-accent': '#4299e1',
        'interactive-accentHover': '#63b3ed',
        'background-hover': '#1A202C',
        'text-primary': '#fff',
        'text-heading': '#f8f9fd',
        'text-danger': '#FC8181',
        'text-muted': '#CBD5E0',
        'background-modifier-border': '#2D3748',
        'sidebar-text': '#CBD5E0',
        'border-color': 'rgba(255, 255, 255, 0.16)',
      },
      light: {
        blue: '#3182ce',
        text: '#fff',
        background: '#000',
        primary: '#33e',
        highlight: '#0c1a1f',
        muted: '#191919',
        overlay: 'rgba(0, 0, 0, 0.7)',
        'background-primary': '#f8f9fd',
        'background-secondary': '#fff',
        'interactive-accent': '#3182ce',
        'interactive-accentHover': '#2b6cb0',
        'background-hover': '#EDF2F7',
        'text-primary': '#1A202C',
        'text-heading': '#495072',
        'text-danger': '#E53E3E',
        'text-muted': '#718096',
        'background-modifier-border': '#dfe0ea',
        'sidebar-text': '#4A5568',
        'border-color': 'rgb(226, 232, 240)',
      },
    },
  },
};

export default theme;
